### ISSUE TITLE
Add link and reference to untriaged issues.

### ISSUE THREAD

**Issue by dunguyen** [visma-prodsec/polaris-slack#1]
It would be useful to have another link where applicable for a project whenever there are untriaged issues. 
The link text could be `(X untriaged issues)` and the link leads to Polaris for the project with the filter of `Issue Status = Open` and `Triage Status = Not Triaged`

**Comment by nathansamson** [comment]
Solved in https://github.com/visma-prodsec/polaris-slack/pull/3 (for google spaces, but should be relatively easy to adapt for slack)

**Comment by nmbro** [comment]
Fixed by #3
